spring:
  application:
    name: gp-api

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  endpoint:
    health:
      show-details: always
      group:
        readiness:
          include: readinessState
        liveness:
          include: livenessState
      probes:
        enabled: true
  health:
    diskspace:
      enabled: false

couchbase:
  hosts: 10.85.247.100
  bucket:
  scope:
  connection:
    connectTimeout: 15s
    kvTimeout: 1s
    queryTimeout: 5s
